services:
  db:
    image: postgres:17.1
    container_name: SafeGuardChatBot_db
    environment:
      POSTGRES_USER: your_postgres_user
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: your_db_name
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - monitor-network

  bot:
    build:
      context: .
    container_name: SafeGuardChatBot
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: your_postgres_user
      DB_PASSWORD: your_postgres_password
      DB_NAME: your_db_name
    ports:
      - "8080:8080"
    restart: always
    networks:
      - monitor-network
    labels:
      - "monitoring.enabled=true"
      - "monitoring.service=bot"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - monitor-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=your_admin_user
      - GF_SECURITY_ADMIN_PASSWORD=your_admin_password
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - monitor-network

networks:
  monitor-network:
    external: true
    name: monitor-network

volumes:
  pgdata:
  grafana-data: