version: '3.8'

services:
  db:
    image: postgres:17.1
    container_name: SafeGuardChatBot_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telegram_logs
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build:
      context: .
    container_name: SafeGuardChatBot
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: telegram_logs

    ports:
      - "8080:8080"
    restart: always

volumes:
  pgdata: