global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'bot'
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets:
          - 'SafeGuardChatBot:8080'
    scrape_timeout: 10s
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090'